CREATE TABLE users (
       id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
       username VARCHAR NOT NULL,
       password_digest VARCHAR,

       CONSTRAINT unique_username UNIQUE(username)
)
