CREATE TABLE points (
       id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
       trip_id integer REFERENCES trips(id),
       name VARCHAR NOT NULL,
       address TEXT,
       coordinates point NOT NULL,
       type VARCHAR NOT NULL,
       notes TEXT,
       schedule json
);
--;;
CREATE INDEX points_trip_id ON points (trip_id);
--;;
CREATE INDEX points_type ON points (type);
